module.exports = {
  visible: [
    'propsToDocumentation',
    'DocumentationOptions',
    'apiDocsConfig',
    'CosmiconfigResult',
    'getRepoPath',
    'NodeKind',
    'TableNode',
    'TableRowNode',
    'TableCellNode',
    'HeadingNode',
    'ParagraphNode',
    'TextNode',
    'BoldNode',
    'EmphasisNode',
    'LinkNode',
    'CodeNode',
    'InlineCodeNode',
    'DocumentationNodeWithChildren',
    'DocumentationNodeWithValue',
  ],
};
